apiVersion : apps/v1
kind: Deployment
metadata:
  name: lladodecidegradlesampleapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lladodecidegradlesampleapp
  template:
    metadata:
      labels:
        app: lladodecidegradlesampleapp 
    spec:
      containers:
        - name: lladodecidegradlesampleapp 
          image: testgradle.azurecr.io/lladodecidegradlesampleapp
          ports:
          - containerPort: 8080